packages:
  - luci
  - adguardhome
  - htop
  - irqbalance
  - kmod-wireguard
  - luci-app-bcp38
  - luci-app-sqm
  - sqm-scripts
  - luci-app-wireguard
  - luci-proto-wireguard
  - wireguard-tools
  - qemu-ga
  - avahi-daemon
config:
  CONFIG_TARGET_ROOTFS_PARTSIZE: 200
