#!/bin/sh /etc/rc.common
 
USE_PROCD=1
START=99
STOP=90

start_service() {
	procd_open_instance cloudflared
	procd_set_param command /usr/bin/cloudflared tunnel --config /etc/cloudflared/config.yaml run
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/cloudflared.pid
	procd_set_param term_timeout 60
	procd_close_instance
}

